export const LOAD_PAGES_REQUEST = 'LOAD_PAGES_REQUEST'
export const LOAD_PAGES_SUCCESS = 'LOAD_PAGES_SUCCESS'
export const LOAD_PAGES_FAILURE = 'LOAD_PAGES_FAILURE'

export const LOAD_PAGE_REQUEST = 'LOAD_PAGE_REQUEST'
export const LOAD_PAGE_SUCCESS = 'LOAD_PAGE_SUCCESS'
export const LOAD_PAGE_FAILURE = 'LOAD_PAGE_FAILURE'

export const CREATE_PAGE_REQUEST = 'CREATE_PAGE_REQUEST'
export const CREATE_PAGE_SUCCESS = 'CREATE_PAGE_SUCCESS'
export const CREATE_PAGE_FAILURE = 'CREATE_PAGE_FAILURE'

export const LOAD_BUSES_SUCCESS = 'LOAD_BUSES_SUCCESS'
export const LOAD_BUS_STOPS_SUCCESS = 'LOAD_BUS_STOPS_SUCCESS'
export const LOAD_BUS_ROUTES_SUCCESS = 'LOAD_BUS_ROUTES_SUCCESS'
