export const LOAD_MASTERS_REQUEST = 'LOAD_MASTERS_REQUEST'
export const LOAD_MASTERS_SUCCESS = 'LOAD_MASTERS_SUCCESS'
export const LOAD_MASTERS_FAILURE = 'LOAD_MASTERS_FAILURE'

export const LOAD_REGISTER_REQUEST = 'LOAD_REGISTER_REQUEST'
export const LOAD_REGISTER_SUCCESS = 'LOAD_REGISTER_SUCCESS'
export const LOAD_REGISTER_FAILURE = 'LOAD_REGISTER_FAILURE'

export const LOAD_REGISTERS_REQUEST = 'LOAD_REGISTERS_REQUEST'
export const LOAD_REGISTERS_SUCCESS = 'LOAD_REGISTERS_SUCCESS'
export const LOAD_REGISTERS_FAILURE = 'LOAD_REGISTERS_FAILURE'
