export const LOAD_MASTERS_REQUEST = 'LOAD_MASTERS_REQUEST'
export const LOAD_MASTERS_SUCCESS = 'LOAD_MASTERS_SUCCESS'
export const LOAD_MASTERS_FAILURE = 'LOAD_MASTERS_FAILURE'

export const LOAD_DISTRICTS_REQUEST = 'LOAD_DISTRICTS_REQUEST'
export const LOAD_DISTRICTS_SUCCESS = 'LOAD_DISTRICTS_SUCCESS'
export const LOAD_DISTRICTS_FAILURE = 'LOAD_DISTRICTS_FAILURE'

export const LOAD_SUBDISTRICTS_REQUEST = 'LOAD_SUBDISTRICTS_REQUEST'
export const LOAD_SUBDISTRICTS_SUCCESS = 'LOAD_SUBDISTRICTS_SUCCESS'
export const LOAD_SUBDISTRICTS_FAILURE = 'LOAD_SUBDISTRICTS_FAILURE'

export const LOAD_ZIPCODE_REQUEST = 'LOAD_ZIPCODE_REQUEST'
export const LOAD_ZIPCODE_SUCCESS = 'LOAD_ZIPCODE_SUCCESS'
export const LOAD_ZIPCODE_FAILURE = 'LOAD_ZIPCODE_FAILURE'

export const LOAD_PARAMCONFIGS_REQUEST = 'LOAD_PARAMCONFIGS_REQUEST'
export const LOAD_PARAMCONFIGS_SUCCESS = 'LOAD_PARAMCONFIGS_SUCCESS'
export const LOAD_PARAMCONFIGS_FAILURE = 'LOAD_PARAMCONFIGS_FAILURE'

export const LOAD_REGISTER_REQUEST = 'LOAD_REGISTER_REQUEST'
export const LOAD_REGISTER_SUCCESS = 'LOAD_REGISTER_SUCCESS'
export const LOAD_REGISTER_FAILURE = 'LOAD_REGISTER_FAILURE'

export const LOAD_REGISTERS_REQUEST = 'LOAD_REGISTERS_REQUEST'
export const LOAD_REGISTERS_SUCCESS = 'LOAD_REGISTERS_SUCCESS'
export const LOAD_REGISTERS_FAILURE = 'LOAD_REGISTERS_FAILURE'
