export Header from './Apps/Header'
export Footer from './Apps/Footer'
export Progress from './Apps/Progress'

export RegisterPage from './Registers/index'
export IdentityForm from './Registers/IdentityForm'
export RegisterForm from './Registers/RegisterForm'
export AgreementModal from './Registers/AgreementModal'
export AlertModal from './Registers/AlertModal'
export ConfirmModal from './Registers/ConfirmModal'
